### PR TITLE
add stm method for 'dgCMatrix' sparse matrix objects

### PR DESCRIPTION
**Pull request by patperry**
This pull request allows one to create term matrices in other R packages (*corpus* and *text2vec*, at least), and analyze them in *stm*.

Example usage:
```r
> x <- corpus::term_matrix(corpus::federalist)
> (model <- stm(x, K = 5, verbose = FALSE))
A topic model with 5 topics, 85 documents and a 8767 word dictionary.
```

### CODE REVIEW

**Comment by bstewart** [comment]
Thanks so much for this Patrick!  I'll let the Travis checks run, but I'll merge when it comes back.

**Comment by bstewart** [comment]
Patrick I think I can fix the issue from here.  Thanks again.

**Comment by patperry** [comment]
Ok, great! Sorry for the extra hassle. Thanks for responding so quickly.

**Comment by bstewart** [comment]
Not at all!  Thanks for doing the work.  Somehow it still amazes me that people just add features on Github.  Open-source is amazing!

**Pull request merged**
