### PR TITLE
Make stm fully compatible with quanteda::dfm()

### PR DESCRIPTION
**Pull request by kbenoit**
What I did:  
-  Redefine `stm()` to work with a **quanteda** dfm  
-  Add **quanteda** to Imports  
-  Edit `stm.Rd` to use **quanteda** in examples  
-  Change references in the vignette to use **quanteda** 

What I did not do (yet):
-  Remove all references to `textProcessor()` and `readCorpus()` in the `.Rd` files, except from `stm.Rd`.  
-  tag `textProcessor()` and `readCorpus()` with `\keyword{internal}` in order to make them not appear in the manual index (but still be accessible using `?textProcessor` and `?readCorpus`.

### CODE REVIEW

**Comment by bstewart** [comment]
Thank you Ken!  I'm backed up with some things but I'm definitely going to carefully review and pull in within the week.

**Comment by bstewart** [comment]
A week I said!  So optimistic...  Anyway I'm working on merging this into the development branch now.  I'm going to leave textProcessor and readCorpus in the manual and I'm changing the behavior to allow meta data to be imported separately or via quanteda.  Otherwise I'm pretty much taking everything.  Thank you so so much for this.

**Comment by bstewart** [comment]
@kbenoit I'm having a bit of trouble with the tests that you set up as well as the examples in the stm documentation.  I think the issue is that they only work on the version of quanteda on github and not the one on cran as they use the new argument names like text_field vs. textField.  Any thoughts on what to do here?  Unfortunately I don't think I'll be able to post it on CRAN because all the tests will fail.

**Comment by bstewart** [comment]
@kbenoit Oh wait never mind- its the other way.  You did do it with the code on CRAN and I have the development version installed.  Sigh...  Thanks!

**Comment by kbenoit** [comment]
OK, and I'm happy to make a modification once we push the new version to CRAN. Although none may be needed since `convert()` has not changed.

**Comment by bstewart** [comment]
Great!  Its just the testing and the examples in the Rd files that will change.  If we push first, you can just let me know when you see it causing a downstream problem.  If we push second, I'll just update to the newest version.

**Comment by kbenoit** [comment]
Sounds good. You can get a GitHub version for the (e.g. Travis) checks by adding the following to `DESCRIPTION` - but I don't think will still work from CRAN.

We currently do this for the [**readtext** package in the GitHub version of **quanteda**](https://github.com/kbenoit/quanteda/blob/master/DESCRIPTION).

```
Remotes: kbenoit/quanteda
```

**Comment by bstewart** [comment]
Oh that's awesome.  Thanks!

**Comment by kbenoit** [comment]
@bstewart I'm closing the PR since I can see you've incorporated the changes into `master` already. 

I don't mind this, but normal practice for a PR is to accept the PR rather than copying in the code in a different way, this way the contributor is credited for the code. As I said it doesn't bother me but is a slight subversion of git/GitHub practice.

Anyway happy to see **stm** and **quanteda** working together now!

**Comment by bstewart** [comment]
Sorry about that Ken!  I need to figure out how to pull in parts of a pull request in to a different branch.  Please know its my comparative ignorance of Github and not a lack of appreciation for your efforts!  I had already put you in the Description as a contributor and under the NEWS file for the latest version.  On the next pull request I'll figure out how to do this the proper git way.

**Comment by kbenoit** [comment]
No worries!

but do see http://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Pull request closed without merging**
