### PR TITLE
Use Roxygen for object doc.

### PR DESCRIPTION
**Pull request by crew102**
This PR addresses the third point in issue #28. A few notes:
- I compared the NAMESPACE file before and after using Roxygen (i.e, your version of NAMESPACE and this PR's version of NAMESPACE) and confirmed that the imported/exported methods align. The only meaningful difference is that several functions that were recently integrated into stm (`expgrad`, `fastAnchor`, etc) are now being exported.
- I reviewed the reference manual after running `system("R CMD Rd2pdf stm")` to make sure that nothing got screwed up in transitioning to Roxygen. Everything looks good.
- I would like to eventually tackle the third point in issue #28 but that won't happen anytime soon. This PR took pretty long time, even with the help of the Rd2roxygen package. Maybe we can agree to start chipping away at this over time? Whenever I see an imported function that I recognize I'll add `::` so stm doesn't have to import it in the future.

### CODE REVIEW

**Comment by crew102** [comment]
Have you seen this before - i.e., where S3 methods don't get exported before Travis builds the vignettes, and thus Travis produces an error if an S3 method is used in a vignette? I've tried reproducing the error a few different ways and I still can't reproduce it.

**Comment by bstewart** [comment]
Thanks so much for all of this.  I haven't seen this problem before.  I'll dig into it and try to work out what is going on.

**Comment by bstewart** [comment]
Okay.  I've found the problem.  This is interesting.  The old code was exporting plot.estimateEffect (and others) both as an S3 and just regularly.  This meant that you could do something like 
`prep <- estimateEffect(...)` and then either `plot(prep)` or `plot.estimateEffect(prep)`.  We found this helpful for R beginners who didn't understand how generics worked.  To make things super clear we essentially always write out `plot.estimateEffect()` in full.  It isn't being exported by Roxygen because it will only do one or the other.  I'm going to post on stackoverflow and see if I can figure out how to override this behavior.  Otherwise I can't see how we can do this without breaking someone's code.

**Comment by bstewart** [comment]
Okay I made some changes and spun this out into pull request #31 .  For the time being I turned off the autocreation of the namespace until I can work out how to preserve the behavior of the old namespace file.

**Comment by crew102** [comment]
What's weird though is that you can use a generic by its full name (i.e., `plot.estimateEffect` or `plot.STM`), just not when Travis is building the vignette. For example, the test that I wrote for `plot.STM` passes when I build locally, and I can build the vignette locally as is without any problems. It's just when it goes to Travis that the generics cannot be used by their full name. 

In other words, generics are exported in both ways (full form and short form), just not before the Travis vignette build.

**Comment by bstewart** [comment]
Oh interesting.  It failed on my machine- not just travis.  And when you look at the namespace it isn't exported.  I don't quite know what to make of that honestly.  When you successfully build and test does the namespace have it listed as exported?

**Comment by crew102** [comment]
Oh you're right, sorry. It's failing on mine. I must of built the vignette and run the tests after running `devtools::load_all()`. I've got a hacky solution for fixing this problem. I'll issue a PR and we can discuss.

**Comment by crew102** [comment]
Nevermind, it's not going to work. I think you're just going to have to not rely on roxygen for the namespace.

**Comment by kbenoit** [comment]
Clearly some tidying still needs to be done to pass the check, but having just generated a [separate **stm** PR](https://github.com/bstewart/stm/pull/34), can voice my very strong support for porting the man pages to **roxygen2**.

On the problem of nixing the `plot.STM()` from the NAMESPACE, @bstewart and I have already discussed it, but I think this is a tiny price to pay for the great benefits of easier to maintain documentation. (And calling `plot.STM()` directly is not standard R behaviour for S3 methods anyway, so this is in many ways "bad" behaviour.)

**Comment by kbenoit** [comment]
If you let me know which PR is the current Roxygen port, I could probably fix the outstanding errors pretty easily.  But is it `crew102:rox` or `pr/30`?

**Comment by bstewart** [comment]
Thanks Ken.  Let me step through and do the first round of fixes and then I may reach out to you for some help.  I'm definitely going to go ahead with it, but I need to make sure the documentation that's been updated since the conversion is carried through.

**Comment by kbenoit** [comment]
Thanks @bstewart. However you prefer is fine. Since I modified some of the Rd files, however, it might be easier to merge in the **quanteda**-related changes before you bring in the other updates. But up you, you can always sort out the merge conflicts.

**Comment by crew102** [comment]
I think it may be possible to have S3 methods be "exported" as S3 methods (e.g., `plot`) and as regular functions (e.g., `plot.stm`)  -  while still using a Roxygen-generated namespace - by exporting those methods as regular functions in `onLoad`. I couldn't figure out how to do this though. Just a thought.

**Comment by bstewart** [comment]
Hi everyone- sorry to have gone quiet on this for so long.  End of semester nonsense.  I just moved all of this into the development branch where I think I have things working.  I'll close this out once I'm sure we have moved over to roxygen

**Comment by kbenoit** [comment]
Happy to help, @bstewart, just holler if you get vexed by the new ways of roxygen2.

**Pull request merged**
