### PR TITLE
parallel searchK

### PR DESCRIPTION
**Pull request by vincentarelbundock**
I wrapped a loop inside ``searchK`` into a function, and added an argument to call ``parallel::mclapply`` for multi-core computation. 

I paste an example of  use below. You'll see that the speed gains are not huge, but keep in mind that this is a toy example with only 3 cores. I'm hoping this change will make a   big difference for my real use case: 10,000s of large documents, with many numbers of topics to examine, on a 20-core machine.

```
library(stm)
library(microbenchmark)
data(gadarian)
corp = stm::textProcessor(gadarian$open.ended.response)

singlecore = function() searchK(corp$documents, corp$vocab, K = 3:8)
multicore = function() searchK(corp$documents, corp$vocab, K = 3:8, cores = 3)
microbenchmark(singlecore(), multicore(), times = 5)

Unit: seconds
         expr       min       lq     mean   median       uq      max neval
 singlecore() 100.55916 110.6592 142.9300 129.3286 182.7562 191.3468     5
  multicore()  98.21267 103.8437 113.2034 104.6925 117.6133 141.6551     5
```

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Test failed on doc error. I ran roxygen again. This should fix it.

**Comment by vincentarelbundock** [comment]
I don't see a test suite for ``searchK``, so I guess we'll have to live with this tiny decrease in coverage...

**Comment by bstewart** [comment]
This is great!  I'm a little overcommitted at the moment but let me dig into it this weekend.

**Comment by iamkbpark** [comment]
Dear @vincentarelbundock  & @bstewart  First of all, I would like to express my sincere appreciation for the stm package! It makes my life way much easier to do `LDA` analysis. One thing I wondered was if `stm` can be run on parallel especially on `searchK()`, and I found this discussion. So, I jumped on to test 'searchK(cores=4)` with the development version re-installed. However, the error says, 
> `"Error in stm(documents = heldout$documents, vocab = heldout$vocab, K = K[i], :  unused argument (cores = 4)"`
Could you please advise what I miss here? Your help will be greatly appreciated.
Thank you in advance.

Sincerely, 
K.B. Park

**Comment by vincentarelbundock** [comment]
Thanks for your interest, but I'm leaving on vacation at this very moment and I won't have time to check for at least a couple of weeks.

Sorry!

**Comment by iamkbpark** [comment]
Thank you for your prompt response even on your vacation! Have fun and I will look forward to the update soon when you get a chance after the vacation! :)

**Comment by vincentarelbundock** [comment]
This is a bit of a ridiculous question, are you sure you installed MY branch? Obviously, since this PR has not been merged into stm's official github master yet, that version won't allow you to use the ``cores`` argument.

**Comment by iamkbpark** [comment]
I used the version of `install_github("bstewart/stm",dependencies=TRUE)`.
Please correct me if I used the wrong one.

**Comment by vincentarelbundock** [comment]
yes, that's the wrong one. install my branch instead.

**Comment by iamkbpark** [comment]
Could you please advise how to install yours? Thank you for your time

**Comment by vincentarelbundock** [comment]
Sorry, but I can't do tech support. This should be very easy to google.

**Comment by iamkbpark** [comment]
Just wanted to share the update of the usage for `searchK(core=8)` from YOUR branch to my test data (K=3:50, 5300 Docs, 7234 vocab).

1. Single Thread = Took 15613.05 sec
2. AWS r4.2xlarge/8 cores: Took 4499.940 sec

It seems `searchK()` with parallel saves lots of time. 
I will also scale up to 500,000 docs for my research project.
Thank you so much for your help and I will look forward to having `searchK()` soon on next release!

**Pull request merged**
