### PR TITLE
Development

### PR DESCRIPTION
**Pull request by bstewart**
All but vignette changes for 1.2

### CODE REVIEW

**Comment by bstewart** [comment]
@kbenoit sorry to both you with this but I think my build of the stm package is failing due to errors on the quanteda on CRAN.  I guess two questions: (1) do you have a potential timeline for the quanteda change and (2) do you have any advice for dealing with issues like this in the short term?  I feel like you are much better at this Travis CI thing than I am.

**Comment by kbenoit** [comment]
Try adding this to `DESCRIPTION`:

```r
Remotes: kbenoit/quanteda
```

We recently resubmitted to CRAN but ran into some incompatibilities with the multi-threading TBB library (C++). I think we've fixed them in the latest master, and plan to resubmit to CRAN tomorrow. In the meantime, pre-CRAN submission, this should avoid any Travis CI issues for you.

As soon as the fully compliant **quanteda** is on CRAN (Saturday?) you can remove that from your `DESCRIPTION` and then submit **stm** to CRAN.

**Comment by bstewart** [comment]
Thank you!  I knew you would have the answer!

**Comment by kbenoit** [comment]
@bstewart I'd be willing to run some tests to see why you had problems building this branch with the CRAN version of **quanteda**, since https://cran.r-project.org/web/checks/check_results_quanteda.html shows that 0.9.9-22 (version as of today) is passing fully except for some unsigned integer issues in C++ code that only Solaris has a problem with (and which we have since fixed in the current GitHub master).

You should not need
```
Remotes: kbenoit/quanteda
```
in `DESCRIPTION`, and this only works on GitHub, not CRAN. I'll work with the `master` branch, since I see you have already merged this PR into the `master`.

Please let me know if I got anything wrong here.

**Comment by bstewart** [comment]
@kbenoit Thanks!  Now that the new version is up on CRAN I'll pull out that one line and run the tests again.  If a problem arises i'll open an issue and link you to it.  Thanks so much for the offer!

**Comment by kbenoit** [comment]
Sounds good. Should be fine as long as you are not compiling or testing on Solaris 😜 
(and anyway we will have that fixed soon too)

**Comment by bstewart** [comment]
Just confirming everything builds cleanly now.  Good luck with Solaris...oh Solaris...

**Pull request merged**
